apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-app-pod
  namespace: prod
  labels:
    app: vulnerable-service
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
    - name: app-container
      image: nginx:latest
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        readOnlyRootFilesystem: false
        capabilities:
          add:
            - SYS_ADMIN
            - NET_ADMIN
            - ALL
      ports:
        - containerPort: 80
      # Intentionally omitting CPU and Memory resource limits & requests
